### ISSUE TITLE
Sprint 2 Meeting Notes

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-03#15]
## Meeting Notes:

**Discussed:**
- Basic functionality and features for each component and overall application data schema. 
- Tempory App Name and Logo with possible themes for final name.

Confirmed using [Jest](https://jestjs.io) a JS & React Testing Framework. Agreed upon a feature and issues-based git workflow with the naming convention of `devName & Feature/Issue Name`.

Confirmed at least six (6) components: Task Tracker, Calendar, Notepad, Pomodoro Timer, Activity Timer, Header maybe Footer.

**Confirmed Meeting Battle Rhythm:**
- Remote Meetings bi-weekly (Towards the beginning and end of the Sprint)
- Periodic Pair Programming w/ Code Review sessions
- Multiple Discord Stand-ups throughout each Sprint
![Voyage10 Schedule](https://user-images.githubusercontent.com/32943879/61091715-30b3cd80-a411-11e9-8357-b45fa92d833b.png)

**Sprint 2 | Priorities:** 
- Finalize MVP with Mockup
- Initial Repo Setup w// License and Meta Data
- Component break down of basic functionality, features, and potentially associated data elements 
- Break down component features and functionality into smaller tasks for current and or future milestones
- Draft Data Schema
- Updating ZenHub with agreed-upon milestones and issues
- Review component resource links

**Assigned (Due posted to ZenHub by 7/11 @ 7 EST):** 
- [ ] @C0LETRA1N to break down **Task Tracker** basic functionality, features, and potentially associated data elements.  As well as break down component features and functionality into smaller tasks for current and or future milestones. 
- [ ] @C0LETRA1N to break down **Calendar** basic functionality, features, and potentially associated data elements. As well as break down component features and functionality into smaller tasks for current and or future milestones. 
- [x] @CodeMeKathy to break down **Notepad** basic functionality, features, and potentially associated data elements. As well as break down component features and functionality into smaller tasks for current and or future milestones.
- [x] @CodeMeKathy to break down **Pomodoro Timer,** basic functionality, features, and likely associated data elements. As well as break down component features and functionality into smaller tasks for current and or future milestones.
- [x] @CodeMeKathy to break down **Activity Timer** basic functionality, features, and potentially associated data elements. As well as break down component features and functionality into smaller tasks for current and or future milestones.

**Assigned:** 
- [ ] @C0LETRA1N Draft Data Schema
- [x] @CodeMeKathy Updating ZenHub with agreed-upon milestones and issues.
- [ ] @C0LETRA1N Incorporate Initial Repo Jest Setup with correlating issue.

#### Task Tracker Component
**- [ ] @C0LETRA1N : Please Insert Links** 

#### Notepad Component
- https://codepen.io/CharlesMThomas/pen/PbNdGM
![React Notepad - Inspiration](https://user-images.githubusercontent.com/32943879/61061344-0d196480-a3ca-11e9-98b8-f7dd3927897b.png)

#### Calendar Component
- [FullCalendar JavaScript Calendar Libraries](https://fullcalendar.io)
- [JavaScript Calendar Libraries](http://jster.net/tag/calendar)
- https://codepen.io/nizarmah/pen/LkjjWV
![Calendar Javascript Inspiration](https://user-images.githubusercontent.com/32943879/61069171-b582f500-a3d9-11e9-9ade-a29500d125e3.png)
![calendar-simple-style Inspiration](https://user-images.githubusercontent.com/32943879/61069330-0b579d00-a3da-11e9-9bee-149e06fcf238.png)

#### Pomodoro Component
- https://codepen.io/jnmorse/pen/KVKVJQ
![Pomodoro Clock Inspiration](https://user-images.githubusercontent.com/32943879/61061881-1ce57880-a3cb-11e9-981b-117723a75451.png)

#### Activity Timer
- https://albert-gonzalez.github.io/easytimer.js/
![Timer Inspiration](https://user-images.githubusercontent.com/32943879/61069141-a734d900-a3d9-11e9-9ba7-88b9117a6d8b.png)

#### Links
- https://www.makeuseof.com/tag/12-gorgeous-chrome-new-tab-extensions-youve-probably-never-tried/
- https://hive.com/blog/productivity-apps/#mcetoc_1cfq3c7p61v
