### ISSUE TITLE
Create Task Tracker Dashboard Component

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-03#5]
## Functionality 

- [ ] A user should be able to create a new task
- [ ] A user should be able to modify an existing task
- [ ] A user should be able to delete an existing task
- [ ] A user should be able to enter a description for the task
- [ ] A user should be able to select a date for the task
- [ ] A user should be able to track time working on the task
- [ ] A user should be able to add notes regarding the task
- [ ] A user should be able to mark a task that needs to be completed as complete
- [ ] A user should be able to mark a task that is completed as incomplete
